name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Lint (non-blocking)
      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff check services || true

      # Unit tests (this is the required gate)
      - name: Unit tests
        run: |
          pip install pytest requests
          pytest -q

      # Optional: try building images, but don't fail CI if Docker hiccups
      - name: Build API image (optional)
        continue-on-error: true
        run: |
          docker build -t api:ci ./services/api

      - name: Build worker image (optional)
        continue-on-error: true
        run: |
          docker build -t worker:ci ./services/worker
